(BE-V511 (CAT V) (DEF "") (EX "If you would hit the building, that would be great.")
 (COMMENTS "Indirect speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (PREP ((ROOT $VAR4) (ROOT IF) (CAT PREP)))
   (AUX ((ROOT $VAR5) (ROOT (WOULD COULD)) (CAT AUX) (OPT +)))
   (V ((ROOT $VAR6) (CAT V)))
   (N ((ROOT $VAR1) (ROOT (THAT IT)) (CAT N)))
   (AUX ((ROOT $VAR2) (ROOT (WILL WOULD)) (CAT AUX)))
   (ROOT $VAR0) (CAT V)
   (ADJ ((ROOT $VAR3) (ROOT (GOOD GREAT)) (CAT ADJ)))
   ))
 (SEM-STRUC
  (REQUEST-ACTION (AGENT (VALUE *SPEAKER*)) (BENEFICIARY HUMAN)
   (THEME (VALUE ^$VAR6)))
  (^$VAR1 (NULL-SEM +)) (^$VAR2 (NULL-SEM +)) (^$VAR3 (NULL-SEM +))
  (^$VAR4 (NULL-SEM +)) (^$VAR5 (NULL-SEM +)))
 (EXAMPLE-BINDINGS
  (IF-4 YOU WOULD-5 HIT-6 THE BUILDING THAT-1 WOULD-2 BE-0 GREAT-3 ))
 (SYNONYMS NIL) (HYPONYMS NIL))

(COULD-AUX500
 (CAT AUX) (DEF "") (EX "Could you please hit the building?")
 (COMMENTS "Direct speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (ROOT $VAR0) (CAT AUX)
   (N ((ROOT $VAR1) (CAT N)))
   (V ((ROOT $VAR3) (CAT V)))
   (PUNCT ((ROOT $VAR4) (ROOT ?) (CAT PUNCT) (OPT +)))
   ))
 (SEM-STRUC
  (MODALITY
   (ATTRIBUTED-TO (VALUE *HEARER*))
   (TYPE EPISTEMIC) (VALUE 0.5) (SCOPE (VALUE ^$VAR3)))
  (^$VAR2 (NULL-SEM +))
  (^$VAR4 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS
  (COULD-0 YOU-1 PLEASE-2 HIT-3 THE BUILDING ?-4))
 (SYNONYMS NIL) (HYPONYMS NIL))

(COULD-AUX510
 (CAT AUX) (DEF "") (EX "Could you please hit the building?")
 (COMMENTS "Indirect speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (ROOT $VAR0) (CAT AUX)
   (N ((ROOT $VAR1) (CAT N)))
   (V ((ROOT $VAR2) (ROOT PLEASE) (CAT V) (OPT +)))
   (V ((ROOT $VAR3) (CAT V)))
   (PUNCT ((ROOT $VAR4) (ROOT ?) (CAT PUNCT) (OPT +)))
   ))
 (SEM-STRUC
  (REQUEST-ACTION
   (AGENT (VALUE *SPEAKER*))
   (BENEFICIARY (VALUE ^$VAR1))
   (THEME (VALUE ^$VAR3)))
  (^$VAR2 (NULL-SEM +))
  (^$VAR4 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS
  (COULD-0 YOU-1 PLEASE-2 HIT-3 THE BUILDING ?-4))
 (SYNONYMS (WOULD)) (HYPONYMS NIL))

(DO-V500
 (CAT V) (DEF "") (EX "Do you have to hit the building?")
 (COMMENTS "Direct speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (ROOT $VAR0) (CAT V)
   (N ((ROOT $VAR1) (CAT N)))
   (AUX ((ROOT $VAR2) (ROOT HAVE) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT INF)))
   (V ((ROOT $VAR4) (CAT V)))
   (PUNCT ((ROOT $VAR5) (ROOT ?) (CAT PUNCT) (OPT +)))
   ))
 (SEM-STRUC
  (REFSEM1
   (MODALITY (TYPE OBLIGATIVE) (VALUE 1) (SCOPE (VALUE ^$VAR2))))
  (REQUEST-INFO
   (AGENT (VALUE *SPEAKER*))
   (BENEFICIARY (VALUE ^$VAR1))
   (THEME (VALUE REFSEM1)))
  (^$VAR2 (NULL-SEM +))
  (^$VAR3 (NULL-SEM +))
  (^$VAR5 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS
  (DO-0 YOU-1 HAVE-2 TO-3 HIT-4 THE BUILDING ?-5))
 (SYNONYMS NIL) (HYPONYMS NIL))

(DO-V510
 (CAT V) (DEF "") (EX "Do you have to hit the building?")
 (COMMENTS "Indirect speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (ROOT $VAR0) (CAT V)
   (N ((ROOT $VAR1) (CAT N)))
   (AUX ((ROOT $VAR2) (ROOT HAVE) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT INF)))
   (V ((ROOT $VAR4) (CAT V)))
   (PUNCT ((ROOT $VAR5) (ROOT ?) (CAT PUNCT) (OPT +)))
   ))
 (SEM-STRUC
  (REFSEM1
   (ASPECT (PHASE END) (SCOPE (VALUE ^$VAR4) (SEM EVENT))))
  (REQUEST-ACTION
   (AGENT (VALUE *SPEAKER*))
   (BENEFICIARY (VALUE ^$VAR1))
   (THEME (VALUE REFSEM1)))
  (^$VAR2 (NULL-SEM +))
  (^$VAR3 (NULL-SEM +))
  (^$VAR5 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS
  (DO-0 YOU-1 HAVE-2 TO-3 HIT-4 THE BUILDING ?-5))
 (SYNONYMS NIL) (HYPONYMS NIL))

(KNOW-V503
 (CAT V) (DEF "") (EX "I would like to know......")
 (COMMENTS "direct speech act. ^$VAR2 WILL ADD THE APPROPRIATE MODALITY") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR6) (CAT N)))
   (AUX ((ROOT $VAR1) (ROOT WOULD) (CAT AUX) (OPT +)))
   (V ((ROOT $VAR2) (ROOT (LIKE WANT NEED)) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT (PREP TO INF))))
   (ROOT $VAR0) (CAT V)
   (PREP ((ROOT $VAR4) (ROOT (IF WHETHER)) (CAT PREP)))
   (V ((ROOT $VAR5) (CAT V)))
   ))
 (SEM-STRUC
  (KNOW
   (AGENT (VALUE ^$VAR6))
   (THEME (VALUE ^$VAR5)))
  (^$VAR1 (NULL-SEM +))
  (^$VAR4 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-6 WOULD-1 LIKE-2 TO-3 KNOW-0 IF-4 YOU HIT-5 THE BUILDING))
 )

(KNOW-V504
 (CAT V) (DEF "") (EX "I would like to know your opinion.")
 (COMMENTS "direct speech act. ^$VAR2 WILL ADD THE APPROPRIATE MODALITY") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR6) (CAT N)))
   (AUX ((ROOT $VAR1) (ROOT WOULD) (CAT AUX) (OPT +)))
   (V ((ROOT $VAR2) (ROOT (LIKE WANT NEED)) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT (PREP TO INF))))
   (ROOT $VAR0) (CAT V)
   (N ((ROOT $VAR5) (CAT N)))
   ))
 (SEM-STRUC
  (KNOW
   (AGENT (VALUE ^$VAR6))
   (THEME (VALUE ^$VAR5)))
  (^$VAR1 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-6 WOULD-1 LIKE-2 TO-3 KNOW-0 YOUR OPINION-5))
 )


(KNOW-V513
 (CAT V) (DEF "") (EX "I WOULD LIKE TO KNOW ...")
 (COMMENTS "indirect speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR6) (CAT N)))
   (AUX ((ROOT $VAR1) (ROOT WOULD) (CAT AUX) (OPT +)))
   (V ((ROOT $VAR2) (ROOT (LIKE WANT NEED)) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT (PREP TO INF))))
   (ROOT $VAR0) (CAT V)
   (PREP ((ROOT $VAR4) (ROOT (IF WHETHER)) (CAT PREP)))
   (V ((ROOT $VAR5) (CAT V)))
   ))
 (SEM-STRUC
  (REQUEST-INFO
   (AGENT (VALUE ^$VAR6))
   (BENEFICIARY (VALUE *HEARER*))
   (THEME (VALUE ^$VAR5))
   )
  (^$VAR1 (NULL-SEM +))
  (^$VAR2 (NULL-SEM +))
  (^$VAR3 (NULL-SEM +))
  (^$VAR4 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-6 WOULD-1 LIKE-2 TO-3 KNOW-0 IF-4 YOU HIT-5 THE BUILDING))
 )

(KNOW-V514
 (CAT V) (DEF "") (EX "I WOULD LIKE TO KNOW NP")
 (COMMENTS "indirect speech act") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR6) (CAT N)))
   (AUX ((ROOT $VAR1) (ROOT WOULD) (CAT AUX) (OPT +)))
   (V ((ROOT $VAR2) (ROOT (LIKE WANT NEED)) (CAT V)))
   (INF ((ROOT $VAR3) (ROOT TO) (CAT (PREP TO INF))))
   (ROOT $VAR0) (CAT V)
   (N ((ROOT $VAR5) (CAT N)))
   ))
 (SEM-STRUC
  (REQUEST-INFO
   (AGENT (VALUE ^$VAR6))
   (BENEFICIARY (VALUE *HEARER*))
   (THEME (VALUE ^$VAR5))
   )
  (^$VAR1 (NULL-SEM +))
  (^$VAR2 (NULL-SEM +))
  (^$VAR3 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-6 WOULD-1 LIKE-2 TO-3 KNOW-0 YOUR OPINION-5))
 )


(WONDER-V501
 (CAT V) (DEF "") (EX "I wonder if X")
 (COMMENTS "direct speech act. ") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR1) (CAT N)))
   (ROOT $VAR0) (CAT V)
   (PREP ((ROOT $VAR2) (ROOT (IF WHETHER)) (CAT PREP)))
   (V ((ROOT $VAR3) (CAT V)))
   ))
 (SEM-STRUC
  (MODALITY (TYPE BELIEF) (VALUE 0.5) (SCOPE (VALUE ^$VAR3))
   (ATTRIBUTED-TO (VALUE ^$VAR1)))  
  (^$VAR2 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-1 WONDER-0 IF-2 YOU HIT-3 THE BUILDING))
 )

(WONDER-V511
 (CAT V) (DEF "") (EX "I wonder if X")
 (COMMENTS "indirect speech act. ") (TMR-HEAD NIL)
 (SYN-STRUC
  ((USE-EXAMPLE-BINDING T)
   (N ((ROOT $VAR1) (CAT N)))
   (ROOT $VAR0) (CAT V)
   (PREP ((ROOT $VAR2) (ROOT (IF WHETHER)) (CAT PREP)))
   (V ((ROOT $VAR3) (CAT V)))
   ))
 (SEM-STRUC
  (REQUEST-INFO
   (AGENT (VALUE ^$VAR1))
   (BENEFICIARY (VALUE *HEARER*))
   (THEME (VALUE ^$VAR3))
   )
  (^$VAR2 (NULL-SEM +))
  )
 (EXAMPLE-BINDINGS (I-1 WONDER-0 IF-2 YOU HIT-3 THE BUILDING))
 )

